### ISSUE TITLE
[SE Issue] 

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/jsdom-fetch-dog-ceo-challenge#9]
### Canvas Link

https://learning.flatironschool.com/courses/1882/assignments/125603?module_item_id=259515

### Concern

I don't believe there are problems with the lab.  However, I found this to be extremely challenging, and now that I have moved to the _next_ lesson I realize that many of my issues fell on the nature of the Fetch function being asynchronous.  Wouldn't it make sense to provide instruction on this before?  

### Additional Context

All necessary context is reported within the concern.

### Suggested Changes

Consider the order of these lessons/labs.

**Comment by ihollander** [comment]
Hi @drewkeat , thanks for this suggestion! The Dog CEO lab is definitely a challenging one. I agree that it would be helpful for students to have the Asynchronous JavaScript lesson come before Dog CEO to help with the mental model of the differences between sync and async code. I'll update the order of these lessons based on your feedback.
